version: 1

formatters:
    simple:
        format: '%(message)s'
    verbose:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: verbose
        filename: link_fin.log
        mode: w

root:
    level: INFO
    handlers: [console, file]

loggers: {}
